### ISSUE TITLE
How to prevent multiple matches?

### ISSUE THREAD

**Issue by JocaPC** [aaditmshah/lexer#15]
I'm trying to transform expressions with eq, le, ne to expressions with =, <=, <>, etc.
Example, transform:
x eq 1 or y le 7
to
x = 1 or y <= 7

However the following code matches eq with two rules eg and /a-z0-9/:
```
require('fs')

Lexer = require('lex');

var l = new Lexer(function (char) {
    throw new Error("Unexpected character: " + char);
});
l.addRule('eq', function () {
    console.log('=');
}).addRule(/ge/, function () {
    console.log('>=');
}).addRule(/gt/gm, function () {
    console.log('>');
}).addRule('le', function () {
    console.log('<=');
}).addRule(/[a-z0-9]+/i, function (lexeme) {
    console.log(lexeme);
}).addRule(/ /i, function (lexeme) {
    //console.log(lexeme);
});

l.input = "x eq 1 or y le 7";

l.lex();
```

For input x eq 1 or y le 7 I'm getting:
```
x
eq
1
or
y
le
7
=
<=
```
"eq" is matched both ar eq and [a-z0-9]+ . How to force lexer not to match eq operator with identifier rule? The output that I need is:
```
x
=
1
or
y
<=
7

```
 It seems that it works only if I specify /ge/ in the rule. For all other format such as 'ge', /ge/i it uses multiple matches.
Is this a bug or expected behavior?

**Comment by aaditmshah** [comment]
Sorry for the late reply. The reason your code doesn't work is because you're applying the `addRule` function to a string instead of a regular expression. The `addRule` function expects a finite regular expression.

A finite regular expression is one which matches at least one character. Hence, it consumes some input. On the other hand, an infinite regular expression is one which can match zero characters. Hence, it consumes no input and the lexer goes into an infinite loop because the same rule is matched indefinitely.

When you apply the `addRule` function to a string instead of a regular expression then it generates the infinite regular expression `/(?:)/g` which matches nothing. That's the reason why `"eq"` matches the rule `/[a-z0-9]+/` instead. At the end of the input there's nothing left to match. However, because `/(?:)/g` matches nothing you get the extra output at the end.

How to force the lexer to not match the identifier rule? Use regular expressions and not strings. Just change your quotes to slashes and everything works fine:

```javascript
var Lexer = require("lex");

var lexer = new Lexer(function (char) { throw new Error("Unexpected char: " + char); })
    .addRule(/eq/, function () { console.log("="); })
    .addRule(/le/, function () { console.log("<="); })
    .addRule(/[a-z0-9]+/, function (lexeme) { console.log(lexeme); })
    .addRule(/\s+/, function () { })
    .setInput("x eq 1 or y le 7");

lexer.lex();
```

When you use `/ge/i` you shouldn't have any problem. The `i` flag means that the match should be case-insensitive. It shouldn't cause any problem and I checked to ensure that it doesn't. It doesn't.

The only problem you have is that you're using strings instead of regular expressions. You shouldn't use strings instead of regular expressions. If you can type `"eq"` then you shouldn't have any problem typing `/eq/` instead.
