### ISSUE TITLE
Questions that actual documentation does not answer...

### ISSUE THREAD

**Issue by jcramalho** [aaditmshah/lexer#17]
Hi, I am using this module as a component in a migrator. I have a few questions:

If I want to pass a variable as an argument to the lexer is it possible? How?
From the documentation I think I understood how start conditions are used but I am missing something: suppose I have two sets of rules in the same lexer, when one set is alive the other is sleeping, and then there is a token that triggers the switch and I want put the sleeping set alive, how do I do that in code?
TIA
jcr

**Comment by aaditmshah** [comment]
What do you mean by pass a variable as an argument to the lexer? Could you show me a code example? If you want to use start conditions then you need to change the `.state` property of the lexer. By default, the lexer is in state `0`. By changing the `.state` property of the lexer you can select which rules are supposed to be applied.

**Comment by jcramalho** [comment]
You should put that statement about start conditions in the documentation. It is important.

I will try to describe the other situation:
	In one of my levers, when I match a rule I want to query a certain data structure to validate some conditions, but this structure is not declared as global, it is declared as a local variable inside the function that calls the lexer. If I want my code to work I have to pass this variable to the lexer, which is declared inside a higher context. I managed to get things running declaring that variable as global but I don’t like this, I have a functional background so I always avoid globals.

I hope I have been clear, I did not send you my code because is too complex and I am using the lexer in a small part of it to do a specific task.

I also teach compiler construction at the local university and I am coding some exercises with your tool. If you want I can send those to you.


One last question, since I am used to lex and flex, what is the correct way or where should I put variable initialisations? And if I want a function to execute when end of input is reached where should I put it?

Thanks and good work, your tool follows nodes principles, simple and efective

jcr

**Comment by aaditmshah** [comment]
Yes, it should be in the documentation. Must have slipped my mind. I'll add it in. Anyway, if your lexer needs to query some local variable then it should be defined in the context of that local variable. This can be done using a lexer factory as follows:

```javascript
function lexerFactory(dataStructure) {
    var lexer = new Lexer;

    lexer.addRule(someRegex, function (lexeme) {
        // do something with dataStructure
    });

    return lexer;
}
```

Now, when you get access to your local data structure you can create a new lexer that uses it as follows:

```javascript
function innerContext() {
    var dataStructure = /* initialize new data structure */;

    var lexer = lexerFactory(dataStructure);

    // use lexer, return it or whatever
}
```

There's no good reason to pass a variable as an argument to the lexer because that creating [tight coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)) between the lexer module and the module using the lexer. Instead, if the lexer needs to use some variable then it should simply be defined in the context of that variable. Hopefully, this answers your second question too. If the lexer is going to use some variable then initialize that variable before defining the lexer.

When the end of the input is reached, calling `lexer.lex` returns `undefined`. Hence, when `lex` returns `undefined` simply call the function you want. Oh, and I'd be happy to see the coding exercises for your compiler construction class.

**Comment by jcramalho** [comment]
Sorry, one more question, how do I have access to the parts of the string that matched marked parts of the regular expression?

Example, consider the following RegExp: /\\def:([a-z][a-z]+)=(.+);/

I want to manipulate strings that matched ([a-z][a-z]+)  and (.+)

I could use start conditions and split the RegExp but other languages and tools let me use $1, $2, …, to access parts.

Can I do it with your tool?

TIA
Jose Carlos Ramalho
Dep. Informatics
University of Minho
http://www.di.uminho.pt/~jcr
